apiVersion: v2
name: helicone-monitoring
description: Helicone Monitoring Stack - Prometheus, Grafana, AlertManager
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kube-prometheus-stack
    version: "61.3.2"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.enabled

keywords:
  - helicone
  - monitoring
  - prometheus
  - grafana

maintainers:
  - name: Helicone Team
    email: engineering@helicone.ai

home: https://helicone.ai
sources:
  - https://github.com/Helicone/helicone 