apiVersion: v1
kind: Secret
metadata:
  name: helicone-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:Helicone/helicone-helm-v3.git
  sshPrivateKey: |
    # REPLACE_WITH_YOUR_SSH_PRIVATE_KEY 