---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helicone-monitoring
  namespace: argocd
  labels:
    app.kubernetes.io/name: helicone-monitoring
    app.kubernetes.io/instance: helicone-monitoring
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:Helicone/helicone-helm-v3.git
    targetRevision: main
    path: charts/helicone-monitoring
    helm: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "3m"
  revisionHistoryLimit: 3

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helicone-infrastructure
  namespace: argocd
  labels:
    app.kubernetes.io/name: helicone-infrastructure
    app.kubernetes.io/instance: helicone-infrastructure
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:Helicone/helicone-helm-v3.git
    targetRevision: main
    path: charts/helicone-infrastructure
    helm: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "3m"
  revisionHistoryLimit: 3
