apiVersion: v2
name: helicone-core
description: Helicone Core Application - Web, Jawn, ClickHouse, MinIO, PostgreSQL
type: application
version: 0.1.4
appVersion: "2025.05.23"

dependencies:
  - name: postgresql
    version: "15.5.20"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: postgresql.enabled

keywords:
  - helicone
  - llm
  - monitoring
  - observability

maintainers:
  - name: Helicone Team
    email: engineering@helicone.ai

home: https://helicone.ai
sources:
  - https://github.com/Helicone/helicone 