apiVersion: v1
kind: Secret
metadata:
  name: helicone-web-secrets
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
type: Opaque
data:
  BETTER_AUTH_SECRET: {{ .Values.helicone.secrets.betterAuthSecret | b64enc }}
  STRIPE_SECRET_KEY: {{ .Values.helicone.secrets.stripeSecretKey | b64enc }}