apiVersion: v2
name: helicone-infrastructure
description: Helicone Infrastructure Components - Cluster Autoscaler, Beyla
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - helicone
  - infrastructure
  - autoscaling
  - observability

maintainers:
  - name: Helicone Team
    email: engineering@helicone.ai

home: https://helicone.ai
sources:
  - https://github.com/Helicone/helicone 