apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.name" . }}-secrets
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ .Values.helicone.secrets.user | b64enc | quote }}