name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Add Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Update chart dependencies and package
        run: |
          mkdir -p .cr-release-packages
          
          for chart in charts/*/Chart.yaml; do
            chart_dir=$(dirname "$chart")
            echo "Processing chart: $chart_dir"
            
            # Check if chart has dependencies
            if grep -q "^dependencies:" "$chart"; then
              echo "Chart has dependencies, updating..."
              cd "$chart_dir"
              helm dependency update
              echo "Dependencies updated, packaging chart..."
              helm package . --destination ../../.cr-release-packages/
              cd - > /dev/null
            else
              echo "Chart has no dependencies, packaging directly..."
              helm package "$chart_dir" --destination .cr-release-packages/
            fi
          done
          
          echo "Packaged charts:"
          ls -la .cr-release-packages/

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_packaging: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"