name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Add Helm dependency repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Update dependencies for charts that need them
        run: |
          # Only update dependencies for charts that have them
          for chart in charts/*/Chart.yaml; do
            chart_dir=$(dirname "$chart")
            if grep -q "^dependencies:" "$chart"; then
              echo "Updating dependencies for $chart_dir"
              cd "$chart_dir"
              helm dependency update
              cd - > /dev/null
            else
              echo "No dependencies found for $chart_dir, skipping"
            fi
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"