name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Add Helm repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Update chart dependencies
        run: |
          for chart in charts/*/Chart.yaml; do
            chart_dir=$(dirname "$chart")
            echo "Updating dependencies for $chart_dir"
            
            # Check if chart has dependencies
            if grep -q "^dependencies:" "$chart"; then
              echo "Chart has dependencies, updating..."
              cd "$chart_dir"
              helm dependency update
              # Extract .tgz dependencies to directories for chart-releaser
              if [ -d charts ]; then
                echo "Charts directory exists, extracting dependencies..."
                cd charts
                ls -la
                for tgz in *.tgz; do
                  if [ -f "$tgz" ]; then
                    echo "Extracting $tgz"
                    tar -xzf "$tgz"
                    echo "Extraction complete, listing contents:"
                    ls -la
                  fi
                done
                cd ..
              else
                echo "No charts directory found"
              fi
              echo "Final chart directory contents:"
              ls -la
              cd - > /dev/null
            else
              echo "Chart has no dependencies, skipping dependency update"
            fi
          done

      - name: Verify extracted dependencies
        run: |
          echo "Checking all chart directories for extracted dependencies:"
          find charts/ -type d -name "postgresql" -exec ls -la {} \; || echo "No postgresql directories found"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"