{{- if .Values.beyla.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helicone.fullname" . }}-beyla
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
    component: beyla
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helicone.fullname" . }}-beyla
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
    component: beyla
rules:
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "services", "nodes"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helicone.fullname" . }}-beyla
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
    component: beyla
subjects:
  - kind: ServiceAccount
    name: {{ include "helicone.fullname" . }}-beyla
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "helicone.fullname" . }}-beyla
{{- end }} 